"""Add schedule_id to assignments

Revision ID: 092eca64884c
Revises: e7f78d95a935
Create Date: 2025-07-25 11:22:39.580240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092eca64884c'
down_revision: Union[str, None] = 'e7f78d95a935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'schedule_id')
    # ### end Alembic commands ###
